version: '3'

services:
  mongo-server:
    image: mongo
    container_name: "mongo-server"
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-server
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-server:27017

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    links:
      - mongo-server
