version: '3'

services:
  mongodb-database:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb-database:27017/

  gateway4:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
                      "spring.data.mongodb.host"  : "mongodb-database",
                      "spring.data.mongodb.port" : "27017",
                      "spring.data.mongodb.database" : "myShop"
                    }'
